### ISSUE TITLE
batch_norm layer

### ISSUE THREAD

**Issue by zhongwen** [auroraxie/Kaggle-NDSB#2]
Have you tried to add batch_norm before **each** non-linearity layer? I tried to use batch_norm on other dataset, but I either suffer from NaN problems or cannot make the logloss lower than random. Could you please tell me the principle of adding batch_norm of your configurations?

**Comment by auroraxie** [comment]
How about adding only one batch_norm layer each time? If it works well, try to add one more, and so on. 
I've tested the performance of adding batch_norm before non-linear layers, and didn't see too many differences at that time.
